export const ADD_FOOD_ERROR = 'ADD_FOOD_ERROR';
export const ADD_FOOD_LOADING = 'ADD_FOOD_LOADING';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';

export const DELETE_FOOD_ERROR = 'DELETE_FOOD_ERROR';
export const DELETE_FOOD_LOADING = 'DELETE_FOOD_LOADING';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';

export const EDIT_FOOD_ERROR = 'EDIT_FOOD_ERROR';
export const EDIT_FOOD_LOADING = 'EDIT_FOOD_LOADING';
export const EDIT_FOOD_SUCCESS = 'EDIT_FOOD_SUCCESS';

export const FETCH_FOODS_ERROR = 'FETCH_FOODS_ERROR';
export const FETCH_FOODS_LOADING = 'FETCH_FOODS_LOADING';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';